baseURL = "https://labgo.thesimplekid.com"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "site title"
theme = "labgo"
enableGitInfo = true
enableRobotsTXT = true

summaryLength = 10

disableKinds = ['taxonomyTerm', 'term']


[params]
    useNetlifyCMS = false
    cloudinary_id= "dgvoxjl5t"
    email = ""
    google_scholar = ""
    copyright = ""
    description = ""